"""add flight table

Revision ID: 787007bb112f
Revises: 
Create Date: 2023-04-02 14:11:41.263356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '787007bb112f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.TEXT(), nullable=False),
    sa.Column('flt', sa.Integer(), nullable=False),
    sa.Column('depdate', sa.Date(), nullable=False),
    sa.Column('dep', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flight_depdate'), 'flight', ['depdate'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flight_depdate'), table_name='flight')
    op.drop_table('flight')
    # ### end Alembic commands ###
